= Getting Started with JBoss EAP 7 on OpenShift


== The Application
The `src/main` folder contains a simple 'Hello world' style Jakarta EE application using JAX-RS.

== Deploying the Quickstart
Make sure you have done all the https://github.com/jboss-eap-up-and-running/docs/blob/main/RUNNING_ON_OPENSHIFT.adoc#prerequisites[prerequisites] and https://github.com/jboss-eap-up-and-running/docs/blob/main/RUNNING_ON_OPENSHIFT.adoc#selecting_creating_a_project[selected/created a project].

Then install the Helm chart contained under link:./charts/helm.yaml[charts/helm.yaml] to install the application into OpenShift.
[source,shell]
----
helm install eap7-getting-started -f charts/helm.yaml jboss-eap/eap74
----

The output of the `helm install` command should contain a line with `STATUS: deployed` that confirms that the Helm release has been deployed.

See the https://github.com/jboss-eap-up-and-running/docs/blob/main/RUNNING_ON_OPENSHIFT.adoc#deploying_with_helm[Deploying with Helm] section for information about when the application will be ready.

.Verification
* Has the Helm release been deployed? 

== Building the application

It may take a few minutes to build the application on OpenShift.
You can watch progress with the command:

[source,shell]
----
oc get build -w
----

The application will be fully built when both builds `eap7-getting-started-build-artifacts-1` and `eap7-getting-started-2` display `Complete` in their `STATUS` column.

.Verification
* Have the builds finished?

== Running the application

To run the application, you can access it through its OpenShift route:

[source,shell]
----
echo https://$(oc get route eap7-getting-started --template='{{ .spec.host }}')
----

.Verification
* Are you able to see the application welcome page when you go to this URL?

== Explaining the application configuration

This application is extremely simple, so apart from the standard information in https://github.com/jboss-eap-up-and-running/docs/blob/main/RUNNING_ON_OPENSHIFT.adoc#introduction_to_helm_charts[Introduction to Helm Charts], link:./charts/helm.yaml[./charts/helm.yaml] contains no additional information.
