= Getting Started with JBoss EAP 7 on OpenShift


== The Application
The `src/main` folder contains a simple 'Hello world' style Jakarta EE application using JAX-RS.

== Deploying the Quickstart
Make sure you have done all the link:../RUNNING_ON_OPENSHIFT.adoc#_prerequisites[prerequisites] and link:../RUNNING_ON_OPENSHIFT.adoc#_selectingcreating_a_project[selected/created a project].

Then install the Helm chart contained under link:./charts/helm.yaml[charts/helm.yaml] to install the application into OpenShift.
[source,shell]
----
helm install eap7-getting-started -f charts/helm.yaml jboss-eap/eap74
----
See the link:../RUNNING_ON_OPENSHIFT.adoc#_deploying_with_helm[Deploying with Helm] section for information about when the application will be ready.

== Running the application

To run the application, you can access it through its OpenShift route:

[source,shell]
----
echo https://$(oc get route eap7-getting-started --template='{{ .spec.host }}')
----

If you use this URL, you will see the welcome page of the application.

== Explaining the application configuration

This application is extremely simple, so apart from the standard information in link:../RUNNING_ON_OPENSHIFT.adoc#_introduction_to_helm_charts[Introduction to Helm Charts], link:./charts/helm.yaml[./charts/helm.yaml] contains no additional information.
